const KEY='control_laboral_v3_2026';
const months=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const seed=[
['2026-01-02','vacaciones',0,1,''],['2026-01-31','extra',6,0,''],['2026-02-21','extra',6,0,''],
['2026-03-14','extra',6,0,''],['2026-03-16','vacaciones',0,1,''],['2026-03-17','vacaciones',0,1,''],['2026-03-18','vacaciones',0,1,''],['2026-03-20','vacaciones',0,1,''],
['2026-05-08','propio',0,2,''],['2026-05-16','extra',6,0,''],['2026-06-06','extra',6,0,''],['2026-06-12','vacaciones',0,1,''],['2026-06-23','extra',6,0,''],
['2026-07-03','propio',0,3,''],['2026-07-18','extra',6,0,''],['2026-08-07','vacaciones',0,1,''],['2026-09-01','vacaciones',0,5,'Semana 36'],['2026-09-08','vacaciones',0,5,'Semana 37'],['2026-09-15','vacaciones',0,5,'Semana 38'],['2026-10-13','vacaciones',0,1,'']
].map((x,i)=>({id:'seed-'+i,date:x[0],type:x[1],hours:x[2],days:x[3],note:x[4]}));
const notes=[{date:'2026-01-01',type:'noche',note:'S.3 Completa'},{date:'2026-02-01',type:'noche',note:'S.6 Completa'},{date:'2026-02-02',type:'noche',note:'S.9 · 3 noches'},{date:'2026-04-01',type:'noche',note:'S.15 Completa'},{date:'2026-05-18',type:'noche',note:'S.18 Completa'},{date:'2026-06-21',type:'noche',note:'S.21 · 4 noches'}].map((x,i)=>({id:'note-'+i,date:x.date,type:x.type,hours:0,days:0,note:x.note}));
function defaults(){return {year:2026,extraPrice:28.84,annualOwn:20,annualVac:23,carryVac:5,boteStart:10,records:[...seed,...notes]}}
let db=JSON.parse(localStorage.getItem(KEY)||'null')||defaults();
function save(){localStorage.setItem(KEY,JSON.stringify(db));}
function totals(){let r=db.records;return {extra:r.filter(x=>x.type==='extra').reduce((a,x)=>a+(+x.hours||0),0),bote:r.filter(x=>x.type==='bote').reduce((a,x)=>a+(+x.hours||0),0)+db.boteStart,vac:r.filter(x=>x.type==='vacaciones').reduce((a,x)=>a+(+x.days||0),0),own:r.filter(x=>x.type==='propio').reduce((a,x)=>a+(+x.days||0),0),nights:r.filter(x=>x.type==='noche').length,travel:r.filter(x=>x.type==='desplazamiento').length}}
const labels={extra:'Horas extra',bote:'Horas de bote',vacaciones:'Vacaciones',propio:'Asunto propio',desplazamiento:'Desplazamiento',noche:'Noche'};
function money(n){return n.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}
function dateES(s){return new Date(s+'T12:00:00').toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit',year:'numeric'})}
function openModal(record){document.getElementById('modal').classList.remove('hidden');document.getElementById('modalTitle').textContent=record?'Editar registro':'Añadir registro';document.getElementById('editId').value=record?.id||'';document.getElementById('rDate').value=record?.date||new Date().toISOString().slice(0,10);document.getElementById('rType').value=record?.type||'extra';document.getElementById('rHours').value=record?.hours||'';document.getElementById('rDays').value=record?.days||'';document.getElementById('rNote').value=record?.note||''}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
document.getElementById('closeModal').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;
document.getElementById('recordForm').onsubmit=e=>{e.preventDefault();const id=document.getElementById('editId').value;const rec={id:id||crypto.randomUUID(),date:document.getElementById('rDate').value,type:document.getElementById('rType').value,hours:+document.getElementById('rHours').value||0,days:+document.getElementById('rDays').value||0,note:document.getElementById('rNote').value.trim()};if(id){db.records=db.records.map(x=>x.id===id?rec:x)}else db.records.push(rec);save();closeModal();render()}
function deleteRec(id){if(confirm('¿Eliminar este registro?')){db.records=db.records.filter(x=>x.id!==id);save();render()}}
function summary(){const t=totals();return `<div class="page-title"><div><h2>Resumen ${db.year}</h2><p>Datos iniciales cargados desde tu archivo de trabajo.</p></div><button class="primary" onclick="openModal()">＋ Añadir registro</button></div><div class="notice">Las horas de <b>bote</b> y las <b>horas extra</b> se mantienen separadas. El bote parte de 10 h y no tiene valor monetario.</div><div class="cards"><div class="card metric"><div class="icon">💶</div><div class="label">Horas extra</div><div class="value">${t.extra} h</div><div class="sub">${money(t.extra*db.extraPrice)}</div></div><div class="card metric"><div class="icon">🧰</div><div class="label">Bote acumulado</div><div class="value">${t.bote} h</div><div class="sub">Incluye ${db.boteStart} h iniciales</div></div><div class="card metric"><div class="icon">🌴</div><div class="label">Vacaciones usadas</div><div class="value">${t.vac} días</div><div class="sub">Disponibles: ${Math.max(0,db.annualVac+db.carryVac-t.vac)} días</div><div class="bar"><i style="width:${Math.min(100,t.vac/(db.annualVac+db.carryVac)*100)}%"></i></div></div><div class="card metric"><div class="icon">📝</div><div class="label">Asuntos propios</div><div class="value">${t.own} días</div><div class="sub">Disponibles: ${Math.max(0,db.annualOwn-t.own)} días</div><div class="bar"><i style="width:${Math.min(100,t.own/db.annualOwn*100)}%"></i></div></div></div><div class="two section"><div class="card"><h3>Resumen por meses</h3><div class="month-grid">${months.map((m,i)=>{let rr=db.records.filter(x=>new Date(x.date+'T12:00:00').getMonth()===i);let ex=rr.filter(x=>x.type==='extra').reduce((a,x)=>a+x.hours,0),bo=rr.filter(x=>x.type==='bote').reduce((a,x)=>a+x.hours,0),va=rr.filter(x=>x.type==='vacaciones').reduce((a,x)=>a+x.days,0);return `<div class="month"><b>${m}</b><div class="mini"><span>Extras</span><strong>${ex} h</strong></div><div class="mini"><span>Bote</span><strong>${bo} h</strong></div><div class="mini"><span>Vacaciones</span><strong>${va} d</strong></div></div>`}).join('')}</div></div><div class="card"><h3>Otros datos</h3><div class="mini"><span>Noches registradas</span><strong>${t.nights}</strong></div><div class="mini"><span>Desplazamientos</span><strong>${t.travel}</strong></div><div class="mini"><span>Precio hora extra</span><strong>${money(db.extraPrice)}</strong></div><div class="mini"><span>Valor extras</span><strong>${money(t.extra*db.extraPrice)}</strong></div></div></div>`}
function calendar(){let now=new Date();let y=db.year,m=now.getMonth();let first=new Date(y,m,1).getDay();first=(first+6)%7;let days=new Date(y,m+1,0).getDate();let cells=[];for(let i=0;i<first;i++)cells.push('<div class="day muted"></div>');for(let d=1;d<=days;d++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ev=db.records.filter(x=>x.date===ds);cells.push(`<div class="day"><div class="daynum">${d}</div>${ev.map(x=>`<div class="event ${x.type}">${labels[x.type]}${x.hours?' · '+x.hours+'h':''}${x.days?' · '+x.days+'d':''}</div>`).join('')}</div>`)}return `<div class="page-title"><div><h2>Calendario</h2><p>Vista del mes actual de ${db.year}. Los registros se guardan en este dispositivo.</p></div><button class="primary" onclick="openModal()">＋ Añadir registro</button></div><div class="card"><div class="calendar-head"><strong>${months[m]} ${y}</strong><span class="note">L · M · X · J · V · S · D</span></div><div class="cal">${['L','M','X','J','V','S','D'].map(x=>`<div class="dow">${x}</div>`).join('')}${cells.join('')}</div></div>`}
function hours(){let rows=db.records.filter(x=>x.type==='extra'||x.type==='bote').sort((a,b)=>b.date.localeCompare(a.date));return `<div class="page-title"><div><h2>Horas</h2><p>Elige siempre si cada apunte es <b>Horas extra</b> o <b>Bote</b>.</p></div><button class="primary" onclick="openModal()">＋ Añadir horas</button></div><div class="cards"><div class="card metric"><div class="label">Horas extra</div><div class="value">${totals().extra} h</div><div class="sub">${money(totals().extra*db.extraPrice)}</div></div><div class="card metric"><div class="label">Bote</div><div class="value">${totals().bote} h</div><div class="sub">Sin valor monetario</div></div></div><div class="table-wrap section"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Horas</th><th>Nota</th><th></th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr><td>${dateES(r.date)}</td><td><span class="pill ${r.type}">${labels[r.type]}</span></td><td><b>${r.hours} h</b></td><td>${r.note||'—'}</td><td class="actions"><button onclick='openModal(${JSON.stringify(r)})'>✏️</button><button onclick="deleteRec('${r.id}')">🗑️</button></td></tr>`).join(''):`<tr><td colspan="5" class="empty">No hay horas registradas.</td></tr>`}</tbody></table></div>`}
function vacations(){let t=totals();return `<div class="page-title"><div><h2>Vacaciones y asuntos propios</h2><p>Control independiente de días disponibles y utilizados.</p></div><button class="primary" onclick="openModal()">＋ Añadir día</button></div><div class="cards"><div class="card metric"><div class="label">Vacaciones</div><div class="value">${t.vac}/${db.annualVac+db.carryVac}</div><div class="sub">${Math.max(0,db.annualVac+db.carryVac-t.vac)} disponibles</div></div><div class="card metric"><div class="label">Año anterior</div><div class="value">${db.carryVac} días</div><div class="sub">Incluidos en el saldo total</div></div><div class="card metric"><div class="label">Asuntos propios</div><div class="value">${t.own}/${db.annualOwn}</div><div class="sub">${Math.max(0,db.annualOwn-t.own)} disponibles</div></div></div><div class="table-wrap section"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Días</th><th>Nota</th><th></th></tr></thead><tbody>${db.records.filter(r=>r.type==='vacaciones'||r.type==='propio').sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<tr><td>${dateES(r.date)}</td><td><span class="pill ${r.type}">${labels[r.type]}</span></td><td><b>${r.days}</b></td><td>${r.note||'—'}</td><td class="actions"><button onclick='openModal(${JSON.stringify(r)})'>✏️</button><button onclick="deleteRec('${r.id}')">🗑️</button></td></tr>`).join('')}</tbody></table></div>`}
function history(){let rows=[...db.records].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="page-title"><div><h2>Historial</h2><p>Todos los movimientos. Puedes editar o eliminar cualquier apunte.</p></div><button class="primary" onclick="openModal()">＋ Añadir registro</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Horas</th><th>Días</th><th>Detalle</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${dateES(r.date)}</td><td><span class="pill ${r.type}">${labels[r.type]}</span></td><td>${r.hours||'—'}</td><td>${r.days||'—'}</td><td>${r.note||'—'}</td><td class="actions"><button onclick='openModal(${JSON.stringify(r)})'>✏️</button><button onclick="deleteRec('${r.id}')">🗑️</button></td></tr>`).join('')}</tbody></table></div>`}
function config(){return `<div class="page-title"><div><h2>Configuración</h2><p>Parámetros del año y herramientas de seguridad.</p></div></div><div class="card"><div class="setting"><div><b>Año</b><div class="note">Año de trabajo actual</div></div><input id="setYear" type="number" value="${db.year}"></div><div class="setting"><div><b>Horas extra · precio/hora</b><div class="note">Se usa solo para calcular el valor de las horas extra</div></div><input id="setPrice" type="number" step="0.01" value="${db.extraPrice}"></div><div class="setting"><div><b>Asuntos propios anuales</b></div><input id="setOwn" type="number" value="${db.annualOwn}"></div><div class="setting"><div><b>Vacaciones anuales</b></div><input id="setVac" type="number" value="${db.annualVac}"></div><div class="setting"><div><b>Vacaciones del año anterior</b></div><input id="setCarry" type="number" value="${db.carryVac}"></div><div class="setting"><div><b>Bote inicial</b><div class="note">Se mantiene separado de las horas extra</div></div><input id="setBote" type="number" step="0.25" value="${db.boteStart}"></div><div class="setting"><div><b>Datos</b><div class="note">Exporta una copia JSON antes de cambiar de dispositivo o navegador.</div></div><div><button class="secondary" onclick="exportData()">Exportar</button> <button class="secondary danger" onclick="resetData()">Restablecer</button></div></div><div style="margin-top:16px;text-align:right"><button class="primary" onclick="saveConfig()">Guardar configuración</button></div></div>`}
function saveConfig(){db.year=+document.getElementById('setYear').value||2026;db.extraPrice=+document.getElementById('setPrice').value||0;db.annualOwn=+document.getElementById('setOwn').value||20;db.annualVac=+document.getElementById('setVac').value||23;db.carryVac=+document.getElementById('setCarry').value||0;db.boteStart=+document.getElementById('setBote').value||0;save();render()}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`control-laboral-${db.year}-backup.json`;a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Esto borrará los datos guardados en este navegador y cargará de nuevo la base inicial. ¿Continuar?')){db=defaults();save();render()}}
document.getElementById('exportBtn').onclick=exportData;document.getElementById('importInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.records)throw 0;db=x;save();render();alert('Copia restaurada correctamente.')}catch{alert('El archivo no es una copia válida de Control Laboral.')}};r.readAsText(f)};
function render(){let view=document.querySelector('nav button.active')?.dataset.view||'resumen';document.getElementById('app').innerHTML=view==='resumen'?summary():view==='calendario'?calendar():view==='horas'?hours():view==='vacaciones'?vacations():view==='historial'?history():config()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});render();
</script></body></html>
